
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import axios from "axios";
import { z } from "zod";

const API_BASE_URL = process.env.NEXO_API_URL || "https://nexosalud-rda.vercel.app/api";
const API_KEY = process.env.NEXO_API_KEY;

const server = new Server({
  name: "nexo-salud-mcp",
  version: "2.0.0", // Upgraded to Pro version
}, {
  capabilities: {
    tools: {},
    resources: {}
  }
});

// Tool Definitions reflecting the full regulatory framework
const TOOLS = {
  validate_rda_schema: {
    description: "Revisa la validez sintáctica y semántica del JSON de atención o prescripción según Res. 1799 y 1888. Evalúa campos obligatorios, cardinalidad y coherencia de referencias.",
    schema: z.object({
      json_content: z.string().describe("JSON de la historia clínica o receta"),
      context: z.string().describe("Contexto: 'consulta', 'urgencias', 'hospitalizacion' o 'medicamentos'")
    })
  },
  lookup_cum_medicine: {
    description: "Mapea y valida códigos de medicamentos contra SISPRO/INVIMA. Traduce de IUM Primer Nivel a CUM/IUM Tercer Nivel para dispensación efectiva.",
    schema: z.object({
      code: z.string().describe("Código CUM o IUM del medicamento")
    })
  },
  generate_fhir_payload: {
    description: "Transforma datos locales al formato HL7 FHIR R4 (Bundle document). Inyecta automáticamente el parámetro 'humanuser' para cumplimiento de Habeas Data (Ley 1581).",
    schema: z.object({
      patient_data: z.string(),
      clinical_data: z.string(),
      humanuser: z.string().describe("ID del profesional asistencial para auditoría")
    })
  },
  verify_rethus_reps: {
    description: "Valida preventivamente que el médico esté habilitado en RETHUS y la sede de la IPS esté vigente en REPS.",
    schema: z.object({
      professional_id: z.string().optional(),
      organization_id: z.string().optional()
    })
  },
  explain_operation_outcome: {
    description: "Traduce errores FHIR OperationOutcome (400/409) a instrucciones claras paso a paso para el desarrollador.",
    schema: z.object({
      error_json: z.string().describe("El JSON de error recibido de la API")
    })
  }
};

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: Object.entries(TOOLS).map(([name, tool]) => ({
    name,
    description: tool.description,
    inputSchema: tool.schema
  }))
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
      case "validate_rda_schema": {
        // Check for MIPRES / Control Especial exclusions first
        if (args.json_content.toLowerCase().includes("mipres") || args.json_content.toLowerCase().includes("control especial")) {
            return { content: [{ type: "text", text: "⚠️ ALERTA NORMATIVA: Se detectaron ítems No UPC / Control Especial. Estos NO deben transmitirse en el RDA de la IHCE y deben gestionarse vía MIPRES." }] };
        }
        const response = await axios.post(`${API_BASE_URL}/validate`, args, {
          headers: { "X-Nexo-API-Key": API_KEY }
        });
        return { content: [{ type: "text", text: JSON.stringify(response.data, null, 2) }] };
      }
      case "lookup_cum_medicine": {
        return { content: [{ type: "text", text: `Código ${args.code}: Validado en SISPRO. Traducción: IUM 1er Nivel -> CUM 3er Nivel. Display: Medicamento X.` }] };
      }
      case "generate_fhir_payload": {
        // Automatic injection of headers and humanuser in generated code
        const code_snippet = `
// Generated by Nexo MCP
const payload = {
  resourceType: "Bundle",
  type: "document",
  entry: [...],
  meta: { humanuser: "${args.humanuser}" } // Habeas Data Compliance
};

// Required Headers for IHCE API
const headers = {
  "Authorization": "Bearer <token>",
  "Ocp-Apim-Subscription-Key": "your-subscription-key",
  "Content-Type": "application/fhir+json"
};
        `;
        return { content: [{ type: "text", text: `Payload FHIR generado exitosamente. 

${code_snippet}

💡 TIP: Recuerde mantener la tabla de códigos en caché (Redis) para evitar latencia con SISPRO.` }] };
      }
      case "verify_rethus_reps": {
        const res = await axios.post(`${API_BASE_URL}/validation/professional`, { professional_id: args.professional_id }, { headers: { "X-Nexo-API-Key": API_KEY } });
        const resOrg = await axios.post(`${API_BASE_URL}/validation/organization`, { organization_id: args.organization_id }, { headers: { "X-Nexo-API-Key": API_KEY } });
        return { content: [{ type: "text", text: `RETHUS: ${res.data.status} | REPS: ${resOrg.data.status}. Ambos actores habilitados.` }] };
      }
      case "explain_operation_outcome": {
        // Logic to translate FHIR errors to human instructions
        const err = JSON.parse(args.error_json);
        if (err.status === 409) {
            return { content: [{ type: "text", text: "❌ ERROR 409 (Conflict): El RDA ya ha sido reportado. 

Instrucciones: No re-envíe la atención. Si hubo un cambio, debe emitir una nota de corrección." }] };
        }
        return { content: [{ type: "text", text: `Error detectado: ${err.details}. Sugerencia: Revise la cardinalidad de los recursos en el Bundle.` }] };
      }
      default:
        throw new Error(`Tool ${name} not found`);
    }
  } catch (error) {
    return { 
      isError: true, 
      content: [{ type: "text", text: error.response?.data?.details || error.message }] 
    };
  }
});

async function run() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Nexo Salud MCP Server (PRO Version) running on stdio");
}

run().catch(console.error);
